[package]
authors = ["Sam Gentle <sam@samgentle.com>"]
name = "cardiograph"
version = "0.1.0"

[dependencies]
bytes = "0.4.4"
futures = "0.1.14"
tokio-core = "0.1.9"
tokio-io = "0.1.2"
tokio-serial = "0.5.0"
tokio-signal = "0.1.2"
clippy = {version = "*", optional = true}

[features]
default = []